config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :ingredients
    end
  end

  resources :recipes, only: [:index, :show] do
    get :search, on: :collection
  end

  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id   :bigint           not null, primary key
#  name :string           not null
#
# Indexes
#
#  index_authors_on_name  (name) UNIQUE
#
class Author < ApplicationRecord
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_ingredients_on_name  (name) UNIQUE
#
class Ingredient < ApplicationRecord
  def self.select_by_name(name)
    where <<-SQL
      name ILIKE '%#{name}%'
    SQL
  end
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id              :bigint           not null, primary key
#  budget          :string
#  image_url       :string
#  ingredient_ids  :integer          default([]), not null, is an Array
#  name            :string           not null
#  original_data   :jsonb            not null
#  people_quantity :integer
#  rate            :integer
#  tag_ids         :integer          default([]), is an Array
#  author_id       :bigint
#
# Indexes
#
#  index_recipes_on_author_id  (author_id)
#
class Recipe < ApplicationRecord
  belongs_to :author

  max_paginates_per 10
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_tags_on_name  (name) UNIQUE
#
class Tag < ApplicationRecord
end

app/controllers/api/v1/ingredients_controller.rb
class Api::V1::IngredientsController < ApplicationController
  def index
    name = params.require(:name)
    @ingredients = Ingredient.select_by_name(name).select(:id, :name)
    render json: @ingredients.pluck(:id, :name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.order(id: :desc).
      page(params[:page]).
      includes(:author)
  end

  def show
    @recipe            = Recipe.find(params[:id])
    @ingredients_names = Ingredient.where(id: @recipe.ingredient_ids).pluck(:name)
    @tags_names        = Tag.where(id: @recipe.tag_ids).pluck(:name)
  end

  def search
    people_quantity = begin
                        Integer(search_params["people_quantity"])
                      rescue
                        nil
                      end
    ingredients_ids = search_params["ingredients"]
    return if ingredients_ids.blank?

    @recipes = Recipe.where('ingredient_ids @> ARRAY[?]', ingredients_ids.map(&:to_i))

    if people_quantity.present?
      @recipes = @recipes.where(people_quantity: people_quantity)
    end

    @recipes = @recipes.page(params[:page]).includes(:author)
  end

  private

  def search_params
    params.require(:recipe)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_recipes.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
		<table class="table table-image">
		  <thead>
		    <tr>
		      <th scope="col">Id</th>
		      <th scope="col">Image</th>
		      <th scope="col">Recipe Name</th>
		      <th scope="col">Rate</th>
		      <th scope="col">Budget</th>
		      <th scope="col">People Quantity</th>
		      <th scope="col">Author</th>
		    </tr>
		  </thead>
		  <tbody>
				<% @recipes.each do |recipe|%>
					<tr>
						<th scope="row"><%= link_to recipe.id, recipe_path(recipe.id) %></th>
						<td class="w-25">
						<% if recipe.image_url.present? %>
								<img src= <%= recipe.image_url %> class="img-fluid img-thumbnail" >
						<% else %>
							No image available
						<% end %>
						</td>
						<td> <%= recipe.name %></td>
						<td> <%= recipe.rate %></td>
						<td> <%= recipe.budget %></td>
						<td> <%= recipe.people_quantity %></td>
						<td> <%= recipe.author.name %></td>
					</tr>
				<% end %>
		  </tbody>
		</table>   
    </div>
  </div>
</div>

<%= paginate @recipes %>

app/views/recipes/_search_form.html.erb
<div class="search_block">
    <button onclick="add()">Add ingredient</button>
    <button onclick="remove()">Remove ingredient</button>

    <%= form_for :recipe, url: { action: :search }, method: :get, html: { id: "recipes_form" } do |f| %>
        <%= f.number_field "people_quantity", step: 1, min: 0, placeholder: "People Quantity" %>
        <div id = "ingredients_lists">
            <div>
                <%= f.text_field :name, class: "ingredient_name", placeholder: "Ingredient name"%>
                <select name='recipe[ingredients][]'></select>
            </div>
        </div>
        <%= f.submit "Search for a recipe"%>
    <% end %>
</div>

<script>

    function add() {
        var new_input = `<input class='ingredient_name'>`;
        var new_select = "<select name='recipe[ingredients][]'></select>"
        $("#ingredients_lists").append(`<div> ${new_input} ${new_select} </div>`);
    }

    function remove() {
        $('#ingredients_lists div:last-child').remove()
    }

    function loadSelects(input_el) {
        const ingredient_name = input_el.value;
        const select_el = input_el.nextElementSibling;

        $.ajax({
            url: "/api/v1/ingredients",
            type: "GET",
            dataType: "json",
            data: {
                "name": ingredient_name
            },
            contentType: "application/json",
        }).then(function (options) {
            options.map(function (option) {
                var opt = document.createElement('option');
                opt.value = option[0];
                opt.innerHTML = option[1];
                select_el.appendChild(opt);
            });
        });
    }

    $('#ingredients_lists').on('keyup keypress', function (e) {
        var keyCode = e.keyCode || e.which;
        if (keyCode === 13) {
            loadSelects(e.target);
            return false;
        }
    });

    $('#recipes_form').on('keyup keypress', function (e) {
        var keyCode = e.keyCode || e.which;
        if (keyCode === 13) {
            e.preventDefault();
            return false;
        }
    });
</script>        

app/views/recipes/index.html.erb
<%= render "search_form" %>
<%= render "recipes" %>

app/views/recipes/search.html.erb
<% if @recipes.present? %>
  <p style="font-size: -webkit-xxx-large;">Results:</p>
  <%= render "recipes" %>
<% else %>
  <p style="font-size: -webkit-xxx-large;">No recipes found</p>
<% end %>

app/views/recipes/show.html.erb
<p style="font-size: -webkit-xxx-large;"><%= @recipe.name %></p>

<% if @recipe.image_url.present? %>
    <img src= <%= @recipe.image_url %> class="img-fluid img-thumbnail" >
<% else %>
  No image available
<% end %>

<div class="container">
  <div class="row">
    <div class="col-12">
		<table class="table table-image">
		  <thead>
		    <tr>
		      <th scope="col">Ingredients</th>
		    </tr>
		  </thead>
		  <tbody>
				<% @ingredients_names.each do |name|%>
					<tr>
						<td> <%= name %></td>
					</tr>
				<% end %>
		  </tbody>
		</table>   
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12">
		<table class="table table-image">
		  <thead>
		    <tr>
		      <th scope="col">Tags</th>
		    </tr>
		  </thead>
		  <tbody>
				<% @tags_names.each do |name|%>
					<tr>
						<td> <%= name %></td>
					</tr>
				<% end %>
		  </tbody>
		</table>   
    </div>
  </div>
</div>